# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harborctl < Formula
  desc "it is a cli client tool for managing harbor robot accounts."
  homepage "https://github.com/ghdwlsgur/harborctl"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/harborctl/releases/download/v1.0.2/harborctl_1.0.2_Darwin_arm64.tar.gz"
      sha256 "5b126838c151e4aad9a2d0d9614bb122f6b2e1405b4b1825fd7192e140472d9b"

      def install
        bin.install "harborctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/harborctl/releases/download/v1.0.2/harborctl_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "d7defae1cf717872922191c120ad66bbfa34cd1cc4c95dfd7e493db625350850"

      def install
        bin.install "harborctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/harborctl/releases/download/v1.0.2/harborctl_1.0.2_Linux_arm64.tar.gz"
      sha256 "fd5512f5b63e95aff29d9894e74f6068d610e385ce829e3d86d8d86de7507e5f"

      def install
        bin.install "harborctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/harborctl/releases/download/v1.0.2/harborctl_1.0.2_Linux_x86_64.tar.gz"
      sha256 "4f0043c4b556c7c4e2ee9c2cda1d5f7e9be15aa362415a73930f013da8d9b3e3"

      def install
        bin.install "harborctl"
      end
    end
  end
end
