# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harborctl < Formula
  desc "it is a cli client tool for managing harbor robot accounts."
  homepage "https://github.com/ghdwlsgur/harborctl"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/harborctl/releases/download/v1.0.1/harborctl_1.0.1_Darwin_arm64.tar.gz"
      sha256 "5c9574b80b25470db99cc3743c54e3d399105ba311c6f0ebdcf3265bad36dc70"

      def install
        bin.install "harborctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/harborctl/releases/download/v1.0.1/harborctl_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "d9b8a024bd81ee46ed5d58eaea91830646c5b20ee393138fca54c5df0f538c96"

      def install
        bin.install "harborctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/harborctl/releases/download/v1.0.1/harborctl_1.0.1_Linux_arm64.tar.gz"
      sha256 "7d31644719ffa88396126ac7a4d097998e740bb6782820cae4aa69ac9b80cccb"

      def install
        bin.install "harborctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/harborctl/releases/download/v1.0.1/harborctl_1.0.1_Linux_x86_64.tar.gz"
      sha256 "ca5a50563b659196aae8be1956634fcd9d897371e735f5a306fd1921ef63ebb7"

      def install
        bin.install "harborctl"
      end
    end
  end
end
